name: easacc_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  intl: ^0.18.1
  #bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  #networking
  dio: ^5.3.3
  http_parser: ^4.0.2
  webview_flutter: ^4.7.0
  network_info_plus: ^4.1.0+1
  #logging
  logger: ^2.0.2+1
  dio_http_formatter: ^3.2.1

  #ui helpers
  flutter_spinkit: ^5.2.0
  toast: ^0.3.0
  #design
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

  # social login
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

  #firebase
  firebase_core: ^2.25.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/icons/
    - assets/translations/
    - assets/icons/

  # example:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf

